NODE=$(shell which node)

# default make target
all: cfg debug

cfg:
	node-gyp configure

debug:
	node-gyp build --debug

clean:
	rm -rf build

run:
	$(NODE) app/4xled7seg/main.js

format:
	@find rpigpiopp -type f \( -name '*.cpp' -o -name '*.h' \) | xargs clang-format -i
	@find app -type f \( -name '*.ts' -o -name '*.js' \) | xargs clang-format -i
